import pandas as pd
from pathlib import Path
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, log_loss
import mlflow
import mlflow.catboost
import joblib

DATA_DIR = Path("data")
MODEL_DIR = Path("model")
MODEL_DIR.mkdir(exist_ok=True)

def train():
    print("🚀 Training Serie A Dummy Classifier...")
    
    # 1. Load Dummy Data (Generated by build_features.py)
    X = pd.read_csv(DATA_DIR / "X_train.csv")
    y = pd.read_csv(DATA_DIR / "y_train.csv")["FullTimeResult"]

    # Simple 80/20 split
    split = int(len(X) * 0.8)
    X_train, X_test = X.iloc[:split], X.iloc[split:]
    y_train, y_test = y.iloc[:split], y.iloc[split:]

    # 2. Track with MLflow
    mlflow.set_experiment("Serie_A_Bootcamp")
    with mlflow.start_run():
        # Keep iterations low so it trains instantly in class
        model = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=4, verbose=0)
        model.fit(X_train, y_train, cat_features=["HomeTeam", "AwayTeam"])

        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)
        loss = log_loss(y_test, model.predict_proba(X_test))

        mlflow.log_metrics({"accuracy": acc, "log_loss": loss})
        
        # Log to MLflow's internal registry
        mlflow.catboost.log_model(model, "SerieAresult_model")

        # 3. Champion vs Challenger Check (USING JOBLIB)
        prod_path = MODEL_DIR / "SerieAresult_model.pkl"
        
        if prod_path.exists():
            # Load the old model using joblib
            old_model = joblib.load(prod_path)
            old_loss = log_loss(y_test, old_model.predict_proba(X_test))
            
            if loss < old_loss:
                print(f"✅ New model beat champion ({loss:.4f} vs {old_loss:.4f})! Updating .pkl.")
                joblib.dump(model, prod_path)
            else:
                print("❌ Champion remains better. Retaining current .pkl model.")
        else:
            print("🆕 No champion found. Saving first .pkl model.")
            joblib.dump(model, prod_path)

if __name__ == "__main__":
    train()